<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RAMESHRIYO" ignored="2" name="Default test(failed)(failed)(failed)" tests="1" failures="1" timestamp="31 Dec 2022 12:16:23 GMT" time="0.065" errors="0">
  <testcase name="tc2" time="0.018" classname="org.group.Employee">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.group.Employee.tc2(Employee.java:19)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc1" time="0.0" classname="org.group.Employee">
    <ignored/>
  </testcase> <!-- tc1 -->
  <testcase name="tc0" time="0.0" classname="org.group.Employee">
    <ignored/>
  </testcase> <!-- tc0 -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
